### ISSUE TITLE
Indent Guide dosn't work everywhere

### ISSUE THREAD

**Issue by Mayeut73** [sschaef/IndentGuide#9]
Hi, I just started to use this plugin in eclipse and it's realy nice, thank you.

But I have installed it on another computer and it's doesn't show. It appears in "preferences", we can change the color or width, but it's dosnt appear on the text editor ...

We have the same version of eclipse ...

I just installed on other eclipse and it's works ...

Realy weird

**Comment by sschaef** [comment]
Hey there,

Did you enable the plugin for the various file types? It needs to be 
done explicitly in the preferences (at the same place where you can 
configure everything else).

Simon

**Comment by Mayeut73** [comment]
Thanks for fast response, Yes it's enable for all files.

Mathieu

**Comment by Mayeut73** [comment]
After re-installed and change some parameters (like the pixel width) it's works, I don't know why ... Thank you for your help
